version: 0.0
os: linux
files:
  - source: /
    destination: /srv/app
hooks:
  AfterInstall:
    - location: deployscripts/afterinstall.sh
      runas: root
  ApplicationStart:
    - location: deployscripts/applicationstart.sh
      runas: root
