# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: f591bd5a0e23737ddb02f307e433e4d17f812e7f618f8fd2e525e9d5856a6cf56acb5cdd98715b552d093e8e3860a6653d9387a37f766e1cc224024e3f20584f

test:
  secret_key_base: 6dd734809c57f67b81de99246e6f3e2d32da1a886de7e876d52163b5fe4044553345b996150cb045d78541a31fdbe131dd785f6747b1f8d5937609276261edc1

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
